# Chapter 3
## Arrays


#### Arrays are the base data type in NumPy, are in similar to lists or tuples since they both contain collections of elements.
### Arrays are initialized from lists (or tuples) using array. Two-dimensional arrays are initialized using lists
of lists (or tuples of tuples, or lists of tuples, etc.), and higher dimensional arrays can be initialized by further
nesting lists or tuples.

In [2]:
from numpy import array

from math import random

x = [0.0,1,2,3,4]
y =array(x)
y

array([0., 1., 2., 3., 4.])

In [3]:
x

[0.0, 1, 2, 3, 4]

In [4]:
type(y)

numpy.ndarray

In [5]:
type(x)

list

In [5]:
y =array([[0.0,1,2,3,4],[5,6,7,8,9]])
y

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]])

In [7]:
y =array ([[1,2],[3,4]],[[5,6],[7,8]])


TypeError: Field elements must be 2- or 3-tuples, got '[5, 6]'

In [8]:
x=array([1.0, 2.0, 3.0, 4.0, 5.0])
x

array([1., 2., 3., 4., 5.])

In [9]:
ndim(x)

NameError: name 'ndim' is not defined

In [10]:
x=array([[1.0,2.0,3.0,4.0,5.0]])

In [11]:
x

array([[1., 2., 3., 4., 5.]])

In [12]:
x = array([[1.0],[2.0],[3.0],[4.0],[5.0]])
x

array([[1.],
       [2.],
       [3.],
       [4.],
       [5.]])

In [13]:
x = array([[1.0,2.0,3.0],[4.0,5.0,6.0],[7.0,8.0,9.0]])
x

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [14]:
x = array([[1.0,2.0],[3.0,4.0]])
y = array([[5.0,6.0],[7.0,8.0]])
z = concatenate((x,y),axis = 0)
z

NameError: name 'concatenate' is not defined

In [15]:
z = vstack((x,y))

NameError: name 'vstack' is not defined

In [17]:
x = linspace(0, 10, 11)
x

NameError: name 'linspace' is not defined

In [19]:
x = range(11)

In [20]:
x

range(0, 11)

In [24]:
x = random.randn(3)

NameError: name 'random' is not defined

In [25]:
x

range(0, 11)

In [28]:
import matplotlib.cm as cm
fig = plt.figure()
ax = Axes3D(fig)
ax.plot_surface(x, y, p, rstride=2, cstride=2, cmap=cm.coolwarm, shade='interp')
ax.view_init(29,80)
plt.draw()

NameError: name 'plt' is not defined